# Generated by Django 4.0.6 on 2023-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0003_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='places',
            name='longitude',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
